# Generated by Django 3.2.7 on 2022-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220323_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('university_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'universities',
            },
        ),
    ]
