# Generated by Django 3.2.7 on 2022-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('HighSchool', models.CharField(max_length=200)),
                ('Subjects', models.CharField(max_length=200)),
                ('Subject1', models.CharField(max_length=200)),
                ('Subject2', models.CharField(max_length=200)),
                ('Subject3', models.CharField(max_length=200)),
                ('Program', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('CareerOption', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'usersData',
            },
        ),
    ]
