# Generated by Django 3.2.7 on 2022-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220323_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=5000)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
