# Generated by Django 3.2.7 on 2022-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_chats_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='title',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
