# Generated by Django 3.2.7 on 2022-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_chats_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='user_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='messages',
            name='user_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
