# Generated by Django 3.2.7 on 2022-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220327_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chats',
            name='messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
