# Generated by Django 3.2.7 on 2022-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220327_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersapi',
            name='access_role',
            field=models.CharField(default='student', max_length=200),
        ),
    ]
