# Generated by Django 3.2.7 on 2022-05-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_usersapi_access_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='access_role',
            field=models.CharField(default='student', max_length=200),
        ),
    ]
